//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp105
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class drehiEntities : DbContext
    {
        public drehiEntities()
            : base("name=drehiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Receipts> Receipts { get; set; }
        public virtual DbSet<ReceiptsProducts> ReceiptsProducts { get; set; }
        public virtual DbSet<StaffInformation> StaffInformation { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
