//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp105
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptsProducts
    {
        public int ID { get; set; }
        public Nullable<int> ReceiptID { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Receipts Receipts { get; set; }
    }
}
