//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp105
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInformation
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string LastName { get; set; }
        public string EGN { get; set; }
        public int Experience { get; set; }
        public string Position { get; set; }
        public decimal Salary { get; set; }
    }
}
